// Copyright (C) 2026 TheHappyAkita
// SPDX-License-Identifier: GPL-3.0-only

import type { QuickNotePlugin } from '#shared/types/plugins'

/**
 * Internal registry for plugins.
 * In a future phase, this could be auto-generated by a Nuxt module
 * scanning the /plugins directory.
 */
export const activePlugins: QuickNotePlugin[] = [
  // Example Plugin: Markdown replacements
  {
    id: 'core-mentions-plus',
    name: 'Mentions Plus',
    version: '1.0.0',
    description: 'Adds extra highlights and shortcodes',
    hooks: {
      'markdown:render': (text: string) => {
        // Example: Replace !!text!! with a warning highlight
        return text.replace(/!!([^!]+)!!/g, '<span class="v-badge v-badge--inline bg-warning px-1 rounded">$1</span>')
      }
    }
  },
  // Example Plugin: Tag suggestion provider
  {
    id: 'tag-suggestions',
    name: 'Tag Suggestions',
    version: '1.0.0',
    description: 'Suggests tags when typing #',
    hooks: {
      'editor:suggestions': () => [{
        trigger: /#([a-zA-Z0-9_-]*)$/,
        mode: 'tag',
        icon: 'mdi-tag',
        color: 'primary',
        getSuggestions: (query: string) => {
          // In a real plugin, you'd fetch tags from a store
          const commonTags = ['work', 'personal', 'idea', 'todo', 'meeting'];
          return commonTags.filter(t => t.startsWith(query));
        },
        formatInsertion: (tag: string) => `#${tag}`
      }]
    }
  },
  // Example Plugin: Custom Theme
  {
    id: 'nord-theme-plugin',
    name: 'Nord Theme',
    version: '1.0.0',
    description: 'Adds the Nord color palette',
    hooks: {
      'ui:themes': () => [{
        id: 'nord',
        label: 'Nord',
        icon: 'mdi-palette',
        dark: true,
        colors: {
          primary: '#88C0D0',
          secondary: '#81A1C1',
          background: '#2E3440',
          surface: '#3B4252',
          error: '#BF616A',
          info: '#EBCB8B',
          success: '#A3BE8C',
          warning: '#D08770',
        }
      }]
    }
  }
]
